-- Apply in the same Supabase database as sirius-cosmical-stock2, after its
-- stock schema and decrement_inventory RPC. Compatible with the existing
-- Spring orders bridge tables, so a future switch to branch front keeps data.
BEGIN;

CREATE TABLE IF NOT EXISTS public.order_catalog_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stock_id uuid NOT NULL REFERENCES public.stocks(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  price numeric(12,2) NOT NULL CHECK (price >= 0 AND price <= 99999999.99),
  imported_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(stock_id, product_id)
);
CREATE INDEX IF NOT EXISTS order_catalog_items_stock ON public.order_catalog_items(stock_id);

CREATE TABLE IF NOT EXISTS public.order_sales (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stock_id uuid NOT NULL REFERENCES public.stocks(id) ON DELETE CASCADE,
  number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  customer text NOT NULL DEFAULT '',
  note text NOT NULL DEFAULT '',
  suggested_total numeric(12,2) NOT NULL CHECK (suggested_total >= 0),
  final_total numeric(12,2) NOT NULL CHECK (final_total >= 0),
  paid numeric(12,2) NOT NULL CHECK (paid >= 0),
  status text NOT NULL DEFAULT 'waiting'
    CHECK (status IN ('waiting','preparing','finished','cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_sales_stock_created ON public.order_sales(stock_id,created_at DESC,id DESC);

CREATE TABLE IF NOT EXISTS public.order_sale_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES public.order_sales(id) ON DELETE CASCADE,
  catalog_item_id uuid REFERENCES public.order_catalog_items(id) ON DELETE SET NULL,
  product_name text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0)
);
CREATE INDEX IF NOT EXISTS order_sale_items_order ON public.order_sale_items(order_id);

ALTER TABLE public.order_catalog_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_sale_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.order_catalog_items, public.order_sales, public.order_sale_items
  FROM PUBLIC, anon, authenticated;

-- Browser users receive no direct table grants. These RPCs check the same
-- stock owner as the stock monolith, then run each write atomically.
CREATE OR REPLACE FUNCTION public.orders_catalog(p_stock_id uuid)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = '' AS $$
DECLARE result jsonb;
BEGIN
  PERFORM public.assert_stock(p_stock_id);
  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'id', c.id, 'sourceProductId', c.product_id, 'sourceStockId', c.stock_id,
    'name', p.name, 'code', p.sku, 'category', coalesce(p.type_name, 'Sem categoria'),
    'isKit', p.is_kit, 'suggestedPrice', coalesce(p.suggested_sale_price, p.next_sale),
    'price', c.price, 'importedAt', c.imported_at
  ) ORDER BY p.name, c.id), '[]'::jsonb) INTO result
  FROM public.order_catalog_items c
  JOIN public.product_catalog p ON p.id = c.product_id
  WHERE c.stock_id = p_stock_id;
  RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.orders_get(p_stock_id uuid, p_order_id uuid)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = '' AS $$
DECLARE result jsonb;
BEGIN
  SELECT jsonb_build_object(
    'id', o.id, 'number', o.number, 'customer', o.customer, 'note', o.note,
    'suggestedTotal', o.suggested_total, 'finalTotal', o.final_total, 'paid', o.paid,
    'status', o.status, 'createdAt', o.created_at, 'updatedAt', o.updated_at,
    'items', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'productId', coalesce(i.catalog_item_id::text, ''),
        'name', i.product_name, 'quantity', i.quantity, 'unitPrice', i.unit_price
      ) ORDER BY i.id)
      FROM public.order_sale_items i WHERE i.order_id = o.id
    ), '[]'::jsonb)
  ) INTO result
  FROM public.order_sales o WHERE o.id = p_order_id AND o.stock_id = p_stock_id;
  RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.orders_list(p_stock_id uuid)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = '' AS $$
DECLARE result jsonb;
BEGIN
  PERFORM public.assert_stock(p_stock_id);
  SELECT coalesce(jsonb_agg(public.orders_get(p_stock_id, o.id)
    ORDER BY o.created_at DESC, o.id DESC), '[]'::jsonb) INTO result
  FROM public.order_sales o WHERE o.stock_id = p_stock_id;
  RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.orders_import_catalog(p_stock_id uuid, p_items jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE entry jsonb; v_product_id uuid; v_catalog_id uuid; product_price numeric; imported uuid[] := '{}';
  seen uuid[] := '{}'; result jsonb;
BEGIN
  PERFORM public.assert_stock(p_stock_id);
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array'
    OR jsonb_array_length(p_items) NOT BETWEEN 1 AND 100 THEN
    RAISE EXCEPTION 'Selecione de 1 a 100 produtos.' USING ERRCODE = '22023';
  END IF;
  PERFORM 1 FROM public.stocks WHERE id = p_stock_id FOR UPDATE;
  FOR entry IN SELECT value FROM jsonb_array_elements(p_items) LOOP
    IF jsonb_typeof(entry) <> 'object'
      OR jsonb_typeof(entry->'price') IS DISTINCT FROM 'number'
      OR nullif(entry->>'sourceProductId', '') IS NULL THEN
      RAISE EXCEPTION 'Produto ou preço inválido.' USING ERRCODE = '22023';
    END IF;
    v_product_id := (entry->>'sourceProductId')::uuid;
    product_price := (entry->>'price')::numeric;
    IF v_product_id = ANY(seen) OR product_price < 0 OR product_price > 99999999.99
      OR product_price <> round(product_price, 2) THEN
      RAISE EXCEPTION 'Produto repetido ou preço inválido.' USING ERRCODE = '22023';
    END IF;
    seen := array_append(seen, v_product_id);
    IF NOT EXISTS (SELECT 1 FROM public.products p
      WHERE p.id = v_product_id AND p.stock_id = p_stock_id AND p.active) THEN
      RAISE EXCEPTION 'Produto não encontrado ou inativo neste estoque.' USING ERRCODE = '22023';
    END IF;
    INSERT INTO public.order_catalog_items(stock_id, product_id, price)
      VALUES (p_stock_id, v_product_id, product_price)
      ON CONFLICT (stock_id, product_id) DO UPDATE
        SET price = excluded.price, imported_at = now()
      RETURNING id INTO v_catalog_id;
    imported := array_append(imported, v_catalog_id);
  END LOOP;
  SELECT coalesce(jsonb_agg(row.value), '[]'::jsonb) INTO result
  FROM jsonb_array_elements(public.orders_catalog(p_stock_id)) AS row(value)
  WHERE (row.value->>'id')::uuid = ANY(imported);
  RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.orders_update_price(
  p_stock_id uuid, p_catalog_id uuid, p_price numeric
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE result jsonb;
BEGIN
  PERFORM public.assert_stock(p_stock_id);
  IF p_price IS NULL OR p_price < 0 OR p_price > 99999999.99
    OR p_price <> round(p_price, 2) THEN
    RAISE EXCEPTION 'Preço inválido.' USING ERRCODE = '22023';
  END IF;
  PERFORM 1 FROM public.stocks WHERE id = p_stock_id FOR UPDATE;
  UPDATE public.order_catalog_items SET price = p_price
    WHERE id = p_catalog_id AND stock_id = p_stock_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Produto importado não encontrado.' USING ERRCODE = 'P0002';
  END IF;
  SELECT row.value INTO result
  FROM jsonb_array_elements(public.orders_catalog(p_stock_id)) AS row(value)
  WHERE (row.value->>'id')::uuid = p_catalog_id;
  RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.orders_create(p_stock_id uuid, p_data jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE entry jsonb; order_id uuid; catalog_id uuid; line record; quantity integer;
  suggested numeric := 0; final_total numeric; paid_amount numeric;
  customer_name text; note_text text; seen uuid[] := '{}';
BEGIN
  PERFORM public.assert_stock(p_stock_id);
  IF p_data IS NULL OR jsonb_typeof(p_data) <> 'object'
    OR jsonb_typeof(p_data->'items') <> 'array'
    OR jsonb_array_length(p_data->'items') NOT BETWEEN 1 AND 100
    OR jsonb_typeof(p_data->'finalTotal') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_data->'paid') IS DISTINCT FROM 'number' THEN
    RAISE EXCEPTION 'Informe os itens e valores do pedido.' USING ERRCODE = '22023';
  END IF;
  customer_name := btrim(coalesce(p_data->>'customer', ''));
  note_text := btrim(coalesce(p_data->>'note', ''));
  final_total := (p_data->>'finalTotal')::numeric;
  paid_amount := (p_data->>'paid')::numeric;
  IF length(customer_name) > 100 OR length(note_text) > 500
    OR final_total < 0 OR final_total > 99999999.99
    OR paid_amount < 0 OR paid_amount > 99999999.99
    OR final_total <> round(final_total, 2) OR paid_amount <> round(paid_amount, 2) THEN
    RAISE EXCEPTION 'Cliente, observação ou valor inválido.' USING ERRCODE = '22023';
  END IF;
  -- Inventory writes lock the stock row as well. One order sees one consistent
  -- catalog/stock state and completion can call the FIFO decrement atomically.
  PERFORM 1 FROM public.stocks WHERE id = p_stock_id FOR UPDATE;
  FOR entry IN SELECT value FROM jsonb_array_elements(p_data->'items') LOOP
    IF jsonb_typeof(entry) <> 'object'
      OR jsonb_typeof(entry->'quantity') IS DISTINCT FROM 'number'
      OR nullif(entry->>'productId', '') IS NULL THEN
      RAISE EXCEPTION 'Item inválido.' USING ERRCODE = '22023';
    END IF;
    catalog_id := (entry->>'productId')::uuid;
    quantity := (entry->>'quantity')::integer;
    IF quantity NOT BETWEEN 1 AND 999 OR catalog_id = ANY(seen) THEN
      RAISE EXCEPTION 'Item repetido ou quantidade inválida.' USING ERRCODE = '22023';
    END IF;
    seen := array_append(seen, catalog_id);
    SELECT c.id, p.name, c.price INTO line
      FROM public.order_catalog_items c JOIN public.products p ON p.id = c.product_id
      WHERE c.id = catalog_id AND c.stock_id = p_stock_id AND p.active;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Um item não pertence ao catálogo deste estoque.' USING ERRCODE = '22023';
    END IF;
    suggested := suggested + line.price * quantity;
  END LOOP;
  INSERT INTO public.order_sales(stock_id, customer, note, suggested_total, final_total, paid)
    VALUES (p_stock_id, customer_name, note_text, suggested, final_total, paid_amount)
    RETURNING id INTO order_id;
  FOR entry IN SELECT value FROM jsonb_array_elements(p_data->'items') LOOP
    SELECT c.id, p.name, c.price INTO line
      FROM public.order_catalog_items c JOIN public.products p ON p.id = c.product_id
      WHERE c.id = (entry->>'productId')::uuid AND c.stock_id = p_stock_id;
    INSERT INTO public.order_sale_items(order_id, catalog_item_id, product_name, quantity, unit_price)
      VALUES (order_id, line.id, line.name, (entry->>'quantity')::integer, line.price);
  END LOOP;
  RETURN public.orders_get(p_stock_id, order_id);
END $$;

CREATE OR REPLACE FUNCTION public.orders_change_status(
  p_stock_id uuid, p_order_id uuid, p_status text
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE previous_status text; sold jsonb;
BEGIN
  PERFORM public.assert_stock(p_stock_id);
  SELECT status INTO previous_status FROM public.order_sales
    WHERE id = p_order_id AND stock_id = p_stock_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Pedido não encontrado.' USING ERRCODE = 'P0002'; END IF;
  IF NOT (
    (previous_status = 'waiting' AND p_status IN ('preparing', 'cancelled'))
    OR (previous_status = 'preparing' AND p_status IN ('finished', 'cancelled'))
    OR (previous_status = 'cancelled' AND p_status = 'waiting')
  ) THEN
    RAISE EXCEPTION 'Transição de status inválida.' USING ERRCODE = '22023';
  END IF;
  IF p_status = 'finished' THEN
    IF EXISTS (SELECT 1 FROM public.order_sale_items i
      LEFT JOIN public.order_catalog_items c ON c.id = i.catalog_item_id
      WHERE i.order_id = p_order_id AND c.product_id IS NULL) THEN
      RAISE EXCEPTION 'Um produto deste pedido não existe mais no estoque.'
        USING ERRCODE = '23514';
    END IF;
    SELECT jsonb_agg(jsonb_build_object(
      'product_id', c.product_id, 'quantity', i.quantity, 'unit', 'un'
    ) ORDER BY i.id) INTO sold
    FROM public.order_sale_items i
    JOIN public.order_catalog_items c ON c.id = i.catalog_item_id
    WHERE i.order_id = p_order_id;
    PERFORM public.decrement_inventory(p_stock_id, 'pedido:' || p_order_id || ':finalizado',
      jsonb_build_object('reason', 'Venda concluída no acompanhamento de pedidos', 'items', sold));
  END IF;
  UPDATE public.order_sales SET status = p_status, updated_at = now()
    WHERE id = p_order_id AND stock_id = p_stock_id;
  RETURN public.orders_get(p_stock_id, p_order_id);
END $$;

-- Internal helper is never callable directly from the browser.
REVOKE ALL ON FUNCTION public.orders_get(uuid,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.orders_catalog(uuid), public.orders_list(uuid),
  public.orders_import_catalog(uuid,jsonb), public.orders_update_price(uuid,uuid,numeric),
  public.orders_create(uuid,jsonb), public.orders_change_status(uuid,uuid,text)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.orders_catalog(uuid), public.orders_list(uuid),
  public.orders_import_catalog(uuid,jsonb), public.orders_update_price(uuid,uuid,numeric),
  public.orders_create(uuid,jsonb), public.orders_change_status(uuid,uuid,text)
  TO authenticated;

NOTIFY pgrst, 'reload schema';
COMMIT;
